global using System.Reflection;
global using System.Text.RegularExpressions;
global using Application;
global using Infrastructure;
global using Infrastructure.Extensions;
global using Application.Common.Models;
global using Common.Interfaces;
global using Common.Extensions;
global using Common.Helpers;